# Generated by Django 5.2.4 on 2025-08-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': ' Shipping Address'},
        ),
    ]
